In [2]:
import numpy as np

In [13]:
#Question -1 Arrays



def arrays(arr):
    # complete this function
    # use numpy.array
    return numpy.array(arr[::-1],float)
    #print(a[::-1])
    
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 4 5 4 9
[9. 4. 5. 4. 1.]


In [7]:
#Question 2--Shape and Reshape

l=list(map(int,input().split()))
arr=np.array(l)
arr.shape=(3,3)
print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#Question 3--Transpose and Flatten


n,m=map(int,input().split())
list1=[]
for i in range (n):
    a = list(map(int,input().split()))
    list1.append(a)
arr=np.array(list1)
print(np.transpose(arr))
print(arr.flatten())

2 2
1 7
5 9
[[1 5]
 [7 9]]
[1 7 5 9]


In [11]:
#Question 4 --Concatenate


n,m,p=map(int,input().split())
list1=[]
list2=[]
for i in range(n):
    a=list(map(int,input().split()))
    list1.append(a)
for i in range(m):
    b=list(map(int,input().split()))
    list2.append(b)
arr1=np.array(list1)
arr2=np.array(list2)
print(np.concatenate((arr1,arr2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [12]:
#Question 5--Zeros and Ones


a=tuple(map(int,input().split()))
print(np.zeros(a,dtype=np.int))
print(np.ones(a,dtype=np.int))

2 2 2
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [16]:
#Question 6--Eye and Identity

a,b=map(int,input().split())
np.set_printoptions(sign=" ")
print(np.eye(a,b))


2 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]


In [15]:
#Question 7--Array Mathematics


A,B=map(int,input().split())
a=np.array([list(map(int,input().split())) for _ in range(A)],int)
b=np.array([list(map(int,input().split())) for _ in range(A)],int)
print(np.add(a,b),np.subtract(a,b),np.multiply(a,b),np.floor_divide(a,b),np.mod(a,b),np.power(a,b),sep="\n")


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [4]:
#Question 8--Sum and Product
a,b=map(int,input().split())
list1=[]
for i in range(a):
    l=list(map(int,input().split()))
    list1.append(l)
arr=np.array(list1)
print(np.prod(np.sum(arr,axis=0),axis=0))


2 2
1 4
3 2
24


In [6]:
#Question 9--Min and Max
a,b=map(int,input().split())
list1=[]
for i in range(a):
    l=list(map(int,input().split()))
    list1.append(l)
arr=np.array(list1)
print(np.max(np.min(arr,axis=1)))

2 4
6 7
8 4
6


In [10]:
# Question 10--Mean, Var, and Std

a,b=list(map(int,input().split()))
arr=np.array([input().split() for i in range(a)],dtype=int)
print(np.mean(arr, axis=1))
print(np.var(arr, axis=0))
np.set_printoptions(sign=" ")
output=np.std(arr)
print(output.round(12))



2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [3]:
#Question 11--Floor, Ceil and Rint
a=list(map(float,input().split()))
arr=np.array(a)
np.set_printoptions(sign=" ")
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [18]:
#Question 12--Linear Algebra
n=int(input())
list1=[]
for i in range(n):
    l1=list(map(float,input().split()))
    list1.append(l1)
arr1=np.array(list1)

p=np.linalg.det(arr1)
print(round(p,2))


2
1.1 1.1
2.2 2.2
0.0


In [22]:
#Question 13--Polynomials

a=list(map(float,input().split()))
x=int(input())
arr=np.array(a)
print(np.polyval(arr,x))


1.1 2 3
0
3.0


In [8]:
#Question 14--Inner and Outer

a=np.array(input().split(),int)
b=np.array(input().split(),int)
print(np.inner(a,b))
print(np.outer(a,b))



0 1
2 3
3
[[0 0]
 [2 3]]


In [9]:
#Question 15--Dot and Cross
n=int(input())
a=np.array([input().split() for _ in range(n)],int)
b=np.array([input().split() for _ in range(n)],int)
c=np.dot(a,b)
print(c)


2
1 4
3 7
2 8
9 5
[[38 28]
 [69 59]]
